[package]
name = "remote-trait-object-tests"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]
edition = "2018"

[dependencies]
codechain-basesandbox = { path = "../basesandbox" }
crossbeam = "0.7.3"
env_logger = "0.7.1"
log = "0.4.8"
once_cell = "1.3.1"
remote-trait-object = {path = "../remote-trait-object"}

[[bin]]
path = "./bin/mod_main.rs"
name = "test_mod_main_rs"

[[bin]]
path = "./bin/mod_ping.rs"
name = "test_mod_ping_rs"
