[package]
name = "remote-trait-object-tests"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]
edition = "2018"

[dependencies]
crossbeam = "0.7.3"

[[bin]]
path = "./bin/mod_main.rs"
name = "test_mod_main_rs"

[[bin]]
path = "./bin/mod_ping.rs"
name = "test_mod_ping_rs"
