// Copyright 2020 Kodebox, Inc.
// This file is part of CodeChain.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use remote_trait_object::*;

pub trait Ping: Service {
    fn ping(&self) -> String;
}

/// TODO: All below things will be generated by the macro

pub struct PingRemote {
    pub handle: Handle,
}

impl Service for PingRemote {}

impl Ping for PingRemote {
    fn ping(&self) -> String {
        let packet = Packet::new_request(self.handle.id, 1, &[]);
        let response = self.handle.port.upgrade().unwrap().call(packet.view());
        String::from_utf8(response.data().to_vec()).unwrap()
    }
}

pub struct PingHandler {
    object: Box<dyn Ping>,
}

impl PingHandler {
    pub fn new(object: Box<dyn Ping>) -> Self {
        Self {
            object,
        }
    }
}

impl Dispatch for PingHandler {
    fn dispatch_and_call(&self, method: MethodId, args: &[u8]) -> Vec<u8> {
        trace!("Ping received {}({:?}) request", method, args);
        if method == 1 {
            self.object.ping().as_bytes().to_vec()
        } else {
            panic!("Dispatch failed: {}({:?})", method, args)
        }
    }
}
